local leveldb = require("leveldb")

describe("dat leveldb", function()
  local db

  setup(function()
    db = leveldb.open("test.db", {create_if_missing=true})
    batch = db:batch()
    batch:put("a", "one")
    batch:put("b", "two")
    batch:put("c", "three")
    batch:write()
  end)

  describe("a call to get()", function()
    describe("for an existing key", function()
      it("should return the value", function()
        assert.are_equal(db:get("a"), "one")
      end)
    end)
    describe("for an non-existent key", function()
      it("should return nil", function()
        assert.is_falsy(db:get("wat"))
      end)
    end)
  end)

  describe("a call to next() on an iterator", function()
    it("should return the next value in the sequence", function()
      iter = db:iterator()
      key, value = iter:next()
      assert.are_equal(key, "a")
      assert.are_equal(value, "b")
    end)
  end)

end)
